export const types = {
    NEW_FILE: 'NEW_FILE',
    MOVE_FILES: 'MOVE_FILES',
    DELETE_FILES: 'DELETE_FILES',
    SET_STATE: 'SET_STATE',
    INCREMENT_COUNT: 'INCREMENT_COUNT',
    DECREMENT_COUNT: 'DECREMENT_COUNT',
    ADD_NEW_REPORT: 'ADD_NEW_REPORT'
};